name: Unity-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #Job 설정
  buildForWindow: 
    name: Build - Windows x64
    runs-on: ubuntu-latest
    steps:
      # Step1 - Check Out
      - name: Check Out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      # Step2 - Cache Library
      - name: Cache Library
        uses: actions/cache@v4
        with: 
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      # Step3 - Unity Build
      - name: Unity Build
        id: build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          # 빌드 결과물 이름을 프로젝트 이름으로 설정
          buildName: ${{ github.event.repository.name }}
      # Step4 - Upload Build File Artifact
      - name: Upload Build File Artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Windows
          path: build
      # Step5 - Create Github Release
      - name: Create a GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Automatically generated releases ${{ github.ref }}
          body:  |
            Automated release for version ${{ github.ref }}.
          draft: false
          prerelease: false
      # Step6 - Upload Build file to Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.artifact.outputs.artifact-url }}
          asset_name: ${{ github.event.repository.name }}-${{ github.ref }}-Windows64.zip
          asset_content_type: application/zip

#  참고: https://dev-junwoo.tistory.com/149 [개발초보 JW의 성장일기:티스토리]
